project:
  type: website

website:
  title: "Visual Analytics and Applications"
  navbar:
    left:
    - text: "Hands-On Exercises"
      menu:
      - text: "Hands-On Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-On Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-On Exercise 3A"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03A.html"
      - text: "Hands-On Exercise 3B"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03B.html"
    - text: "In-Class Exercises"
      menu:
      - text: "In-Class Exercise 1"
        href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
    - text: "Take-home Exercises"
      menu:
      - text: "Take-Home Exercise 1"
        href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
    right:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: About
    
format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

