project:
  type: website

website:
  title: "Rach's Visual Portfolio"
  image: "images/title1.png"
  favicon: "images/title1.png"
  page-navigation: true
  
  navbar:
    logo: "images/title1.png"
    title: false
    collapse-below: lg
    search: true
    left:
    - text: "Hands-On Exercises"
      menu:
      - text: "Hands-On Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-On Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-On Exercise 3A"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03A.html"
      - text: "Hands-On Exercise 3B"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03B.html"
      - text: "Hands-On Exercise 4A"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04A.html"
      - text: "Hands-On Exercise 4B"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04B.html"
      - text: "Hands-On Exercise 4C"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04C.html"
      - text: "Hands-On Exercise 4D"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04D.html"
    - text: "In-Class Exercises"
      menu:
      - text: "In-Class Exercise 1"
        href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
    - text: "Take-home Exercises"
      menu:
      - text: "Take-Home Exercise 1"
        href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
      - text: "Take-Home Exercise 2"
        href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
    right:
    - icon: house
      href: https://isss608-rachyrm.netlify.app/
      aria-label: Home
    - icon: person-lines-fill
      href: https://isss608-rachyrm.netlify.app/about
      aria-label: About
    - icon: github
      href: https://github.com/rachyrm/ISSS608-VAA
      aria-label: GitHub
    - icon: linkedin
      href: https://www.linkedin.com/in/rachelyrm/
      aria-label: LinkedIn
    
format:
  html:
    theme: 
      - minty
      - theme.scss
    highlight-style: kate
    code-copy: hover
    code-overflow: wrap
    css: styles.css
    toc: true

editor: visual
